-- -------------------------------------------------------------
-- 
-- File Name: D:\codegen\dwt2_hdl\hdlsrc\dwt2_hdl_fixpt_pkg.vhd
-- Created: 2025-05-11 03:36:31
-- 
-- Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE dwt2_hdl_fixpt_pkg IS
  TYPE matrix_of_std_logic_vector14 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(13 DOWNTO 0);
  TYPE matrix_of_unsigned14 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF unsigned(13 DOWNTO 0);
  TYPE matrix_of_signed14 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_unsigned7 IS ARRAY (NATURAL RANGE <>) OF unsigned(6 DOWNTO 0);
  TYPE vector_of_signed29 IS ARRAY (NATURAL RANGE <>) OF signed(28 DOWNTO 0);
  TYPE vector_of_signed28 IS ARRAY (NATURAL RANGE <>) OF signed(27 DOWNTO 0);
END dwt2_hdl_fixpt_pkg;


